"""llms.txt — publication shape + consumption guidance drift guards.

Sprint llms-txt (2026-06-10). Two halves, both instruction-level by
frontier convergence (Claude Code WebFetch does not auto-probe
``/llms.txt``; LangChain mcpdoc pairs an explicit tool with a prompt
rule; Codex CLI puts site guidance in AGENTS.md — silent fetch-tool
probing has no frontier precedent):

* PUBLICATION — ``site/public/llms.txt`` (generated by
  ``site/scripts/sync-stats.mjs``, regenerated on every Pages deploy)
  must keep the llmstxt.org shape: H1 → blockquote summary → H2
  link-list sections (``- [name](url): notes``) → ``## Optional``.
* CONSUMPTION — the agentic suffix (``router.md``) carries the
  llms.txt-first research heuristic and the ``web_fetch`` tool
  description advertises it. Both are visible instructions, not hidden
  behavior; these tests pin them against silent removal.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LLMS_TXT = REPO_ROOT / "site" / "public" / "llms.txt"
LLMS_FULL_TXT = REPO_ROOT / "site" / "public" / "llms-full.txt"
DEFINITIONS = REPO_ROOT / "core" / "tools" / "definitions.json"

_LINK_LINE = re.compile(r"^- \[[^\]]+\]\(https?://[^)]+\)")


def test_agentic_suffix_carries_llms_txt_heuristic() -> None:
    from core.llm.prompts import AGENTIC_SUFFIX

    assert "/llms.txt" in AGENTIC_SUFFIX
    assert "llms-full.txt" in AGENTIC_SUFFIX
    # The heuristic must instruct ORDER (index first), not just mention the file.
    assert "FIRST" in AGENTIC_SUFFIX


def test_web_fetch_description_advertises_llms_txt() -> None:
    data = json.loads(DEFINITIONS.read_text(encoding="utf-8"))
    tools = data["tools"] if isinstance(data, dict) and "tools" in data else data
    web_fetch = next(t for t in tools if isinstance(t, dict) and t.get("name") == "web_fetch")
    assert "/llms.txt" in web_fetch["description"]


def test_published_llms_txt_is_spec_conformant() -> None:
    lines = LLMS_TXT.read_text(encoding="utf-8").splitlines()
    assert lines[0] == "# GEODE", "H1 must be the first line (llmstxt.org)"
    assert lines[2].startswith("> "), "blockquote summary must follow the H1"

    h2_sections = [ln for ln in lines if ln.startswith("## ")]
    assert len(h2_sections) >= 3, "expected H2 file-list sections"
    assert "## Optional" in h2_sections, "spec's skippable-links section"

    link_lines = [ln for ln in lines if ln.startswith("- ")]
    assert link_lines, "file-list sections must carry link items"
    bad = [ln for ln in link_lines if not _LINK_LINE.match(ln)]
    assert not bad, f"non-markdown link lines (plain-text regression): {bad[:3]}"


def test_published_llms_full_txt_keeps_sections() -> None:
    """The 2026-05-29 docs redesign silently broke the sitemap section
    parser (title/titleKo moved to separate lines) — every page lost its
    section header. Pin that sections survive."""
    content = LLMS_FULL_TXT.read_text(encoding="utf-8")
    assert content.count("\n## ") >= 3, "section H2s missing — sitemap parser drift"
