#!/usr/bin/env python3
"""Bake Geodi terminal assets -> core/ui/geodi_art.py + core/ui/geodi_img.py.

Two products, both from the SVGs via Quick Look:
  * geodi_img.py  — the real sprite as a transparent PNG (base64). Terminals that
    speak the Kitty (Ghostty/kitty) or iTerm2 image protocol draw this directly.
  * geodi_art.py  — a solid half-block ANSI fallback for image-less terminals,
    baked from the *bold icon* variant so it stays legible when tiny.

Keying only white (qlmanage flattens transparency to white) keeps the dark
eyes/mouth as pixels. Runtime prints the baked constants — no image at runtime.

Run:  uv run python scripts/visualizations/geodi_ansi.py
"""

import base64
import io
import json
import math
import subprocess
import tempfile
from pathlib import Path

from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
CUTE_SVG = ROOT / "site/public/images/geodi.svg"  # full detail (eyes open) -> inline image
BLINK_SVG = ROOT / "site/public/images/geodi-blink.svg"  # eyes closed -> blink frames
SWAY_L_SVG = ROOT / "site/public/images/geodi-sway-l.svg"  # gill crown swayed left
SWAY_R_SVG = ROOT / "site/public/images/geodi-sway-r.svg"  # gill crown swayed right
ICON_SVG = ROOT / "site/public/images/geodi-icon.svg"  # bold -> block-art fallback
ART_OUT = ROOT / "core/ui/geodi_art.py"
IMG_OUT = ROOT / "core/ui/geodi_img.py"
WIDTH = 16  # block-art columns (each cell = 1px wide x 2px tall)
ALPHA = 110
ESC = "\x1b"


def _is_bg(r, g, b):
    """White (what qlmanage flattens transparency to). Keeps dark eyes/mouth."""
    return r > 248 and g > 248 and b > 248


def _keyed_raw(svg, size=240):
    """Render via Quick Look and key the white background to transparency (uncropped)."""
    with tempfile.TemporaryDirectory() as d:
        subprocess.run(
            ["qlmanage", "-t", "-s", str(size), "-o", d, str(svg)], check=True, capture_output=True
        )
        src = Image.open(Path(d) / (svg.name + ".png")).convert("RGB")
    keyed = Image.new("RGBA", src.size)
    sp, kp = src.load(), keyed.load()
    for y in range(src.height):
        for x in range(src.width):
            r, g, b = sp[x, y]
            kp[x, y] = (r, g, b, 0 if _is_bg(r, g, b) else 255)
    return keyed


def _keyed(svg, size):
    """Keyed sprite, tight-cropped to its alpha bounding box."""
    im = _keyed_raw(svg, size)
    return im.crop(im.split()[3].getbbox())


def _cell(top, bot):
    ta, ba = top[3] >= ALPHA, bot[3] >= ALPHA
    if ta and ba:
        return f"{ESC}[38;2;{top[0]};{top[1]};{top[2]};48;2;{bot[0]};{bot[1]};{bot[2]}m▀"
    if ta:
        return f"{ESC}[49;38;2;{top[0]};{top[1]};{top[2]}m▀"
    if ba:
        return f"{ESC}[49;38;2;{bot[0]};{bot[1]};{bot[2]}m▄"
    return f"{ESC}[0m "


def bake_art():
    im = _keyed(ICON_SVG, 320)
    h = round(im.height * WIDTH / im.width)
    h += h % 2
    im = im.resize((WIDTH, h), Image.LANCZOS)
    px = im.load()
    w, hh = im.size
    lines = [
        ("".join(_cell(px[x, y], px[x, y + 1]) for x in range(w)) + f"{ESC}[0m")
        for y in range(0, hh, 2)
    ]
    assert lines and all(ESC in ln for ln in lines), "empty art"
    ART_OUT.write_text(
        '"""Geodi terminal art — baked half-block ANSI (bold icon, image-less fallback).\n\n'
        'Generated by scripts/visualizations/geodi_ansi.py; do not hand-edit."""\n\n'
        "GEODI_ART: list[str] = [\n" + "".join(f"    {json.dumps(ln)},\n" for ln in lines) + "]\n"
    )
    return len(lines)


BOB = 6  # bob travel in px
FRAMES = 12  # animation frames per loop
BLINK_AT = (5, 6)  # frame indices whose eyes are closed (a quick blink)


def _png_b64(canvas):
    buf = io.BytesIO()
    canvas.save(buf, "PNG")
    data = buf.getvalue()
    return data, base64.b64encode(data).decode()


def _erode_crop(raw, bbox):
    """Crop a keyed sprite to the shared bbox and erode the 2px anti-alias fringe."""
    im = raw.crop(bbox)
    a = im.split()[3]
    for _ in range(2):
        a = a.filter(ImageFilter.MinFilter(3))
    im.putalpha(a)
    return im


def bake_img():
    # 4 source states (eyes open, eyes shut, gills swayed L/R). One shared (union)
    # bbox keeps every frame aligned so the head bobs/blinks/flutters in place.
    raws = {
        n: _keyed_raw(p)
        for n, p in (("op", CUTE_SVG), ("bl", BLINK_SVG), ("sl", SWAY_L_SVG), ("sr", SWAY_R_SVG))
    }
    boxes = [im.split()[3].getbbox() for im in raws.values()]
    bbox = (
        min(b[0] for b in boxes),
        min(b[1] for b in boxes),
        max(b[2] for b in boxes),
        max(b[3] for b in boxes),
    )
    op, bl, sl, sr = (_erode_crop(raws[n], bbox) for n in ("op", "bl", "sl", "sr"))
    w, h = op.size

    def frame(src, y):  # sprite on a bob-tall canvas at vertical offset y
        c = Image.new("RGBA", (w, h + BOB), (0, 0, 0, 0))
        c.alpha_composite(src, (0, y))
        return c

    frames = []
    for i in range(FRAMES):
        y = round(BOB / 2 * (1 - math.cos(2 * math.pi * i / FRAMES)))  # ease-in-out bob
        if i in BLINK_AT:
            src = bl  # quick blink
        else:
            s = math.sin(2 * math.pi * i / FRAMES)  # gill sway L <-> R over the loop
            src = sl if s < -0.35 else sr if s > 0.35 else op
        frames.append(frame(src, y))
    rest = frame(op, round(BOB / 2))
    rest_data, rest_b64 = _png_b64(rest)
    frames_b64 = [_png_b64(f)[1] for f in frames]

    prev = Image.new("RGBA", rest.size, (11, 10, 16, 255))
    prev.alpha_composite(rest)
    prev.convert("RGB").resize((rest.width * 3, rest.height * 3)).save(
        Path.home() / ".geode" / "diagnostics" / "geodi_img_preview.png"
    )
    IMG_OUT.write_text(
        '"""Geodi inline-image data — transparent PNGs (base64) of the full sprite.\n\n'
        "Generated by scripts/visualizations/geodi_ansi.py; do not hand-edit.\n"
        "GEODI_PNG_* is the resting frame; GEODI_FRAMES is a bob loop the CLI cycles\n"
        'through (Ghostty/kitty draw static images only). See core/ui/mascot.py."""\n\n'
        f"GEODI_PNG_SIZE = {len(rest_data)}\n"
        f"GEODI_PNG_B64 = {json.dumps(rest_b64)}\n\n"
        "GEODI_FRAMES: list[str] = [\n"
        + "".join(f"    {json.dumps(f)},\n" for f in frames_b64)
        + "]\n"
    )
    return len(rest_data), len(frames_b64)


def main():
    (Path.home() / ".geode" / "diagnostics").mkdir(parents=True, exist_ok=True)
    rows = bake_art()
    size, nframes = bake_img()
    print(
        f"geodi_art.py <- {rows} rows x {WIDTH} cols · geodi_img.py <- {size}B rest + {nframes} frames"
    )


if __name__ == "__main__":
    main()
