"""Frozen experiment contracts for Crucible campaigns."""

from .contract import (
    Budget,
    ContractError,
    ExperimentContract,
    Mutation,
    PromotionRule,
    content_sha256,
    load_contract,
    task_pack_sha256,
    tracked_tree_sha256,
    validate_candidate_diff,
    validate_checkout,
    validate_measurement_files,
    validate_shards,
    validate_test_parent,
)
from .evidence import (
    EvidenceEnvelope,
    ResourceUsage,
    TaskEvidence,
    load_evidence,
    validate_evidence_identity,
)
from .promotion import PromotionVerdict, decide
from .supervisor import (
    CandidateProducer,
    CandidateProposal,
    EvaluationArtifacts,
    FailureFeedback,
    LoopLimits,
    PromotionSupervisor,
    SupervisorConfig,
    SupervisorError,
    SupervisorSummary,
    TrainPlan,
    TrustedEvaluator,
    run_supervisor,
)

__all__ = [
    "Budget",
    "CandidateProducer",
    "CandidateProposal",
    "ContractError",
    "EvaluationArtifacts",
    "EvidenceEnvelope",
    "ExperimentContract",
    "FailureFeedback",
    "LoopLimits",
    "Mutation",
    "PromotionRule",
    "PromotionSupervisor",
    "PromotionVerdict",
    "ResourceUsage",
    "SupervisorConfig",
    "SupervisorError",
    "SupervisorSummary",
    "TaskEvidence",
    "TrainPlan",
    "TrustedEvaluator",
    "content_sha256",
    "decide",
    "load_contract",
    "load_evidence",
    "run_supervisor",
    "task_pack_sha256",
    "tracked_tree_sha256",
    "validate_candidate_diff",
    "validate_checkout",
    "validate_evidence_identity",
    "validate_measurement_files",
    "validate_shards",
    "validate_test_parent",
]
