"""llms.txt — publication shape + consumption guidance drift guards.

Sprint llms-txt (2026-06-10), upgraded by PR-LLMS-TXT-TOOL (2026-06-12):
consumption is now a dedicated ``llms_txt_index`` tool (mcpdoc
convergence — explicit tool paired with a prompt rule; still no silent
fetch-tool probing, the heuristic instructs the call order visibly):

* PUBLICATION — ``site/public/llms.txt`` (generated by
  ``site/scripts/sync-stats.mjs``, regenerated on every Pages deploy)
  must keep the llmstxt.org shape: H1 → blockquote summary → H2
  link-list sections (``- [name](url): notes``) → ``## Optional``.
* CONSUMPTION — the agentic suffix (``router.md``) carries the
  llms.txt-first research heuristic (``llms_txt_index`` first, then
  ``web_fetch`` the picked pages), the ``web_fetch`` tool description
  advertises it, and the ``llms_txt_index`` tool is wired through
  definitions.json + the delegated-handler registry. The tool's parser
  behaviour is guarded by ``tests/core/tools/test_llms_txt_index.py``;
  these tests pin the visible instructions + wiring against silent
  removal.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
LLMS_TXT = REPO_ROOT / "site" / "public" / "llms.txt"
LLMS_FULL_TXT = REPO_ROOT / "site" / "public" / "llms-full.txt"
DEFINITIONS = REPO_ROOT / "core" / "tools" / "definitions.json"

_LINK_LINE = re.compile(r"^- \[[^\]]+\]\(https?://[^)]+\)")


def test_agentic_suffix_carries_llms_txt_heuristic() -> None:
    from core.llm.prompts import AGENTIC_SUFFIX

    assert "/llms.txt" in AGENTIC_SUFFIX
    assert "llms-full.txt" in AGENTIC_SUFFIX
    # The heuristic must instruct ORDER (index first), not just mention the file.
    assert "FIRST" in AGENTIC_SUFFIX
    # PR-LLMS-TXT-TOOL — step 1 is the dedicated tool, not a raw web_fetch.
    assert "llms_txt_index" in AGENTIC_SUFFIX


def test_web_fetch_description_advertises_llms_txt() -> None:
    data = json.loads(DEFINITIONS.read_text(encoding="utf-8"))
    tools = data["tools"] if isinstance(data, dict) and "tools" in data else data
    web_fetch = next(t for t in tools if isinstance(t, dict) and t.get("name") == "web_fetch")
    assert "/llms.txt" in web_fetch["description"]
    assert "llms_txt_index" in web_fetch["description"]


def test_llms_txt_index_tool_is_wired() -> None:
    """definitions.json entry + delegated-handler registry + SAFE_TOOLS —
    a definition without a handler (or vice versa) is a half-wired tool."""
    data = json.loads(DEFINITIONS.read_text(encoding="utf-8"))
    tools = data["tools"] if isinstance(data, dict) and "tools" in data else data
    index_def = next(t for t in tools if isinstance(t, dict) and t.get("name") == "llms_txt_index")
    assert index_def["input_schema"]["required"] == ["url"]
    assert "/llms.txt" in index_def["description"]
    assert "web_fetch" in index_def["description"], "must hand off page fetch to web_fetch"

    from core.cli.tool_handlers.delegated import _DELEGATED_TOOLS

    assert _DELEGATED_TOOLS["llms_txt_index"] == ("core.tools.llms_txt", "LlmsTxtIndexTool")

    from core.agent.safety import SAFE_TOOLS

    assert "llms_txt_index" in SAFE_TOOLS, "read-only tool must be sub-agent auto-approvable"


def test_published_llms_txt_is_spec_conformant() -> None:
    lines = LLMS_TXT.read_text(encoding="utf-8").splitlines()
    assert lines[0] == "# GEODE", "H1 must be the first line (llmstxt.org)"
    assert lines[2].startswith("> "), "blockquote summary must follow the H1"

    h2_sections = [ln for ln in lines if ln.startswith("## ")]
    assert len(h2_sections) >= 3, "expected H2 file-list sections"
    assert "## Optional" in h2_sections, "spec's skippable-links section"

    link_lines = [ln for ln in lines if ln.startswith("- ")]
    assert link_lines, "file-list sections must carry link items"
    bad = [ln for ln in link_lines if not _LINK_LINE.match(ln)]
    assert not bad, f"non-markdown link lines (plain-text regression): {bad[:3]}"


def test_published_llms_full_txt_keeps_sections() -> None:
    """The 2026-05-29 docs redesign silently broke the sitemap section
    parser (title/titleKo moved to separate lines) — every page lost its
    section header. Pin that sections survive."""
    content = LLMS_FULL_TXT.read_text(encoding="utf-8")
    assert content.count("\n## ") >= 3, "section H2s missing — sitemap parser drift"


def test_published_llms_txt_docs_links_target_md_twins() -> None:
    """PR-LLMS-TXT-MD-TWINS — docs links must point at the clean markdown
    twins (rendered URL + .md), not the Next.js-rendered HTML pages an LLM
    pays hydration-payload tokens for."""
    lines = LLMS_TXT.read_text(encoding="utf-8").splitlines()
    docs_links = [ln for ln in lines if ln.startswith("- ") and "github.io/geode/docs" in ln]
    assert docs_links, "no docs links in llms.txt"
    bad = [ln for ln in docs_links if ".md)" not in ln]
    assert not bad, f"docs links still target rendered pages: {bad[:3]}"


def test_published_llms_full_txt_carries_page_content() -> None:
    """llms-full.txt must be the TRUE full-content dump the llmstxt.org
    convention promises (it used to be a summary-only index — the
    'no markdown twins yet' era). Written post-build by export-docs-md.mjs."""
    content = LLMS_FULL_TXT.read_text(encoding="utf-8")
    assert len(content) > 100_000, "llms-full.txt regressed to a summary-only index"
    assert "```" in content, "page bodies (code fences) missing — index-only regression"
    assert "\nMarkdown: https://" in content, "per-page .md twin links missing"
    # Indirect balanced-extraction pin (Codex review of PR #2218, finding 1):
    # the changelog page nests 300+ inner <article>s; only a COMPLETE
    # extraction exceeds the llms-full body cap and earns the explicit
    # omission note. If extraction regresses to first-</article> truncation,
    # the body shrinks under the cap and this note disappears.
    assert "body omitted from llms-full" in content, (
        "changelog body under cap — nested-<article> extraction truncated again?"
    )


def test_md_twin_export_is_wired_into_pages_deploy() -> None:
    """The twins are build artifacts (converted from the static-export
    HTML), so the export step must run in pages.yml after `npm run build`
    — a script that exists but never runs ships zero twins. Single-writer
    pin: sync-stats.mjs must NOT write llms-full.txt anymore."""
    pages_yml = (REPO_ROOT / ".github" / "workflows" / "pages.yml").read_text(encoding="utf-8")
    build_at = pages_yml.index("npm run build")
    export_at = pages_yml.index("npm run export-md")
    assert export_at > build_at, "export-md must run AFTER the static build"

    export_script = REPO_ROOT / "site" / "scripts" / "export-docs-md.mjs"
    assert export_script.exists(), "export-docs-md.mjs missing"
    assert "llms-full.txt" in export_script.read_text(encoding="utf-8")

    sync_stats = (REPO_ROOT / "site" / "scripts" / "sync-stats.mjs").read_text(encoding="utf-8")
    assert "writeLlmsFullTxt" not in sync_stats, (
        "sync-stats writes llms-full.txt again — two writers for one file"
    )
