#!/usr/bin/env python3

"""check_docs_canon — banned-term audit of the docs site against the content canon.

GEODE's self-improving loop is **not** machine learning: no weight, parameter,
or policy update ever happens. The loop mutates the scaffold (system-prompt
sections + behaviour kinds) and selects via adversarial safety audit
(``site/CONTENT-CANON.md`` §2). Docs prose that frames the loop as "ML",
"training", "RL", or "fine-tuning" therefore mischaracterises the product.

This script walks the docs surface and flags banned vocabulary:

* ``site/src/app/docs/**/*.tsx`` (page bodies)
* ``site/src/app/page.tsx`` (landing)
* ``site/src/components/geode-docs/**/*.tsx`` (shared docs chrome)

Excluded by design:

* ``site/src/data/`` — generated by ``sync-stats.mjs`` (CHANGELOG quotes are
  historical record, not product framing).
* ``site/src/app/portfolio/`` — separate narrative surface with its own rules.

Waiver: a line containing ``canon-ok`` is skipped. Use it where a banned term
is unavoidable in a lineage / comparison context (e.g. "unlike RL, ...") or in
a correct negation ("does not run gradient descent").

Exit codes:

* 0 — no banned terms
* 1 — at least one banned term
* 2 — argparse / IO error

Usage::

    python scripts/check_docs_canon.py                # audit site/src
    python scripts/check_docs_canon.py --base site    # alt site root
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WAIVER_MARKER = "canon-ok"

# Each entry: (label, compiled pattern). Patterns target *mischaracterising*
# phrases; correct negations that still match must carry the waiver marker.
BANNED_TERMS: list[tuple[str, re.Pattern[str]]] = [
    (
        "ml-loop",
        re.compile(
            r"ML\s*(?:실험\s*)?루프|머신\s*러닝\s*루프"
            r"|machine[\s-]?learning\s+loop|\bML\s+(?:experiment\s+)?loop",
            re.IGNORECASE,
        ),
    ),
    (
        "learning-loop",
        re.compile(r"학습\s*루프|\blearning\s+loop\b|\bself-learning\b", re.IGNORECASE),
    ),
    ("reinforcement", re.compile(r"강화\s*학습|reinforcement\s+learning|\bRL\b")),
    ("fine-tuning", re.compile(r"파인\s*튜닝|fine-?tun(?:e|ed|es|ing)\b", re.IGNORECASE)),
    ("reward-model", re.compile(r"리워드\s*모델|reward\s+model", re.IGNORECASE)),
    ("dpo", re.compile(r"\bDPO\b")),
    (
        "weight-update",
        re.compile(r"가중치\s*(?:갱신|업데이트|학습)|weight\s+update", re.IGNORECASE),
    ),
    ("gradient", re.compile(r"경사\s*하강|gradient\s+descent|backprop", re.IGNORECASE)),
]

# File-scoped waivers, keyed by path relative to the site root, valued by the
# banned-term labels that file may legitimately contain. Reserved for pages
# whose *subject* is the comparison with ML systems, where the term describes
# another system or appears inside a rendered <pre> diagram (so an inline
# marker would leak into the visible output). Keep this list short; prefer the
# inline ``canon-ok`` marker everywhere else.
FILE_WAIVERS: dict[str, frozenset[str]] = {
    # Literature-quadrant comparison: "weight update (RLHF family)" axis labels
    # and "prompt evolution can beat RL" cite other systems, not GEODE.
    "src/app/docs/capabilities/lineage/page.tsx": frozenset({"weight-update", "reinforcement"}),
    # Frontier table: "Autonomous ML loop" / "Self-learning agent" describe
    # Karpathy autoresearch and Hermes respectively, in their own words.
    "src/app/docs/reference/frontier-comparison/page.tsx": frozenset({"ml-loop", "learning-loop"}),
}


def docs_surface_files(site_root: Path) -> list[Path]:
    """Collect the docs-surface source files the canon governs."""
    app_root = site_root / "src" / "app"
    chrome_root = site_root / "src" / "components" / "geode-docs"
    collected: list[Path] = sorted((app_root / "docs").rglob("*.tsx"))
    landing = app_root / "page.tsx"
    if landing.exists():
        collected.append(landing)
    if chrome_root.exists():
        collected.extend(sorted(chrome_root.rglob("*.tsx")))
    sitemap_source = site_root / "src" / "lib" / "geode-docs" / "sitemap.ts"
    if sitemap_source.exists():
        collected.append(sitemap_source)
    return collected


def scan_file(source_path: Path, waived_labels: frozenset[str]) -> list[tuple[int, str, str]]:
    """Return (line_no, label, line_text) violations for one file."""
    violations: list[tuple[int, str, str]] = []
    source_lines = source_path.read_text(encoding="utf-8").splitlines()
    for line_no, line_text in enumerate(source_lines, start=1):
        if WAIVER_MARKER in line_text:
            continue
        for label, pattern in BANNED_TERMS:
            if label not in waived_labels and pattern.search(line_text):
                violations.append((line_no, label, line_text.strip()))
    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Audit docs prose for canon-banned vocabulary.")
    parser.add_argument("--base", default="site", help="site root (default: site)")
    parsed = parser.parse_args(argv)

    site_root = Path(parsed.base)
    if not (site_root / "src" / "app").is_dir():
        print(f"error: {site_root}/src/app not found", file=sys.stderr)
        return 2

    total = 0
    for source_path in docs_surface_files(site_root):
        relative_key = source_path.relative_to(site_root).as_posix()
        waived_labels = FILE_WAIVERS.get(relative_key, frozenset())
        for line_no, label, line_text in scan_file(source_path, waived_labels):
            total += 1
            print(f"{source_path}:{line_no}: [{label}] {line_text[:120]}")

    if total:
        print(
            f"\n{total} banned term(s). The self-improving loop is selection over a"
            " scaffold, not ML (site/CONTENT-CANON.md §2). Rephrase, or add a"
            f" `{WAIVER_MARKER}` marker on lines where the term is a deliberate"
            " comparison or negation.",
            file=sys.stderr,
        )
        return 1
    print("docs canon: clean (no banned terms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
