"""Automation Ports — Protocol interfaces for L4.5 automation components.

Defines abstract contracts for DriftDetector, ModelRegistry, ExpertPanel,
CorrelationAnalyzer, OutcomeTracker, SnapshotManager, TriggerManager,
and FeedbackLoop, enabling Clean Architecture dependency inversion.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DriftDetectorPort(Protocol):
    """Protocol for CUSUM drift detection."""

    @property
    def stats(self) -> Any: ...

    def add_baseline(self, metric_name: str, values: list[float]) -> None: ...
    def detect(self, metric_name: str, value: float) -> Any: ...
    def scan_all(self, values: dict[str, float]) -> list[Any]: ...
    def reset(self, metric_name: str | None = None) -> None: ...
    def get_baseline(self, metric_name: str) -> tuple[float, float] | None: ...
    def list_metrics(self) -> list[str]: ...


@runtime_checkable
class ModelRegistryPort(Protocol):
    """Protocol for versioned model registry."""

    @property
    def stats(self) -> Any: ...

    def register(
        self,
        version_id: str,
        *,
        parent: str | None = None,
        configs: dict[str, Any] | None = None,
        prompt_text: str = "",
        rubric_text: str = "",
        metrics: dict[str, float] | None = None,
    ) -> Any: ...

    def promote(
        self,
        version_id: str,
        target_stage: Any,
        *,
        validation_fn: Callable[..., bool] | None = None,
    ) -> Any: ...
    def rollback(self, version_id: str) -> Any: ...
    def get_production(self) -> Any | None: ...
    def get_version(self, version_id: str) -> Any | None: ...
    def list_versions(self, stage: Any | None = None) -> list[Any]: ...


@runtime_checkable
class ExpertPanelPort(Protocol):
    """Protocol for expert panel management."""

    @property
    def stats(self) -> Any: ...

    def add_expert(self, expert: Any) -> None: ...
    def remove_expert(self, expert_id: str) -> bool: ...
    def get_expert(self, expert_id: str) -> Any | None: ...
    def list_experts(self, tier: Any | None = None) -> list[Any]: ...
    def collect_ratings(
        self,
        item_id: str,
        scores: dict[str, float],
        confidences: dict[str, float] | None = None,
    ) -> list[Any]: ...
    def compute_consensus(
        self,
        ratings: list[Any],
        weights: dict[str, float] | None = None,
    ) -> dict[str, Any]: ...


@runtime_checkable
class CorrelationAnalyzerPort(Protocol):
    """Protocol for score correlation analysis."""

    @property
    def stats(self) -> Any: ...

    def compute_spearman(self, x: list[float], y: list[float]) -> tuple[float, float]: ...
    def compute_kendall(self, x: list[float], y: list[float]) -> tuple[float, float]: ...
    def full_analysis(
        self,
        auto_scores: list[float],
        human_scores: list[float],
        k: int = 10,
        quarter: str = "",
    ) -> Any: ...
    def check_targets(self, result: Any, quarter: str | None = None) -> dict[str, bool]: ...


@runtime_checkable
class OutcomeTrackerPort(Protocol):
    """Protocol for outcome collection job management."""

    @property
    def stats(self) -> Any: ...

    def schedule(self, ip_name: str, tracking_point: Any, *, max_retries: int = 3) -> Any: ...
    def execute_job(self, job_id: str, outcome: Any) -> Any: ...
    def fail_job(self, job_id: str, error: str) -> Any: ...
    def get_job(self, job_id: str) -> Any | None: ...
    def list_jobs(self, ip_name: str | None = None, status: Any | None = None) -> list[Any]: ...
    def get_outcomes(self, ip_name: str) -> list[Any]: ...


@runtime_checkable
class SnapshotManagerPort(Protocol):
    """Protocol for pipeline state snapshot management."""

    def capture(
        self,
        session_id: str,
        *,
        pipeline_state: dict[str, Any] | None = None,
        context: dict[str, Any] | None = None,
        prompt_hash: str = "",
        rubric_hash: str = "",
        config_hash: str = "",
    ) -> Any: ...

    def restore(self, snapshot_id: str) -> Any: ...
    def list_snapshots(self, session_id: str | None = None) -> list[Any]: ...
    def prune(self, max_recent: int | None = None) -> int: ...
    def delete(self, snapshot_id: str) -> bool: ...


@runtime_checkable
class TriggerManagerPort(Protocol):
    """Protocol for pipeline trigger management."""

    @property
    def stats(self) -> Any: ...

    @property
    def is_scheduler_running(self) -> bool: ...

    def register(self, config: Any) -> None: ...
    def unregister(self, trigger_id: str) -> bool: ...
    def get_trigger(self, trigger_id: str) -> Any | None: ...
    def list_triggers(self, trigger_type: Any | None = None) -> list[Any]: ...
    def fire_manual(self, trigger_id: str, data: dict[str, Any] | None = None) -> Any: ...
    def make_event_handler(self, trigger_id: str) -> Callable[..., None]: ...
    def start_scheduler(self) -> None: ...
    def stop_scheduler(self) -> None: ...
    def register_pipeline_trigger(
        self,
        trigger_id: str,
        ip_name: str,
        *,
        trigger_type: Any = None,
        cron_expr: str = "",
        callback: Callable[..., Any] | None = None,
    ) -> Any: ...
    def get_results(self, trigger_id: str | None = None, limit: int = 100) -> list[Any]: ...


@runtime_checkable
class SchedulerServicePort(Protocol):
    """Protocol for advanced job scheduling (3-type + active hours)."""

    @property
    def is_running(self) -> bool: ...

    def add_job(self, job: Any) -> None: ...
    def remove_job(self, job_id: str) -> bool: ...
    def update_job(self, job_id: str, **updates: Any) -> bool: ...
    def get_job(self, job_id: str) -> Any | None: ...
    def list_jobs(self, include_disabled: bool = False) -> list[Any]: ...
    def run_now(self, job_id: str) -> dict[str, Any]: ...
    def start(self, interval_s: float = 60.0) -> None: ...
    def stop(self) -> None: ...
    def save(self) -> None: ...
    def load(self) -> None: ...


@runtime_checkable
class FeedbackLoopPort(Protocol):
    """Protocol for RLHF feedback loop."""

    @property
    def stats(self) -> Any: ...

    def collect(self, cycle_input: Any) -> dict[str, Any]: ...
    def analyze(self, cycle_input: Any) -> dict[str, Any]: ...
    def propose_improvement(self, analysis_result: dict[str, Any]) -> list[Any]: ...
    def run_cycle(self, cycle_input: Any) -> Any: ...
    def get_history(self, limit: int = 10) -> list[Any]: ...
