"""Orchestration Ports — Protocol interfaces for orchestration components.

Defines abstract contracts for RunLog, CoalescingQueue, ConfigWatcher,
LaneQueue, StuckDetector, and TaskGraph, enabling Clean Architecture
dependency inversion.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class RunLogPort(Protocol):
    """Protocol for run logging."""

    @property
    def file_path(self) -> Path: ...

    def append(self, entry: Any) -> None: ...

    def read(
        self,
        *,
        limit: int = 100,
        offset: int = 0,
        event_filter: str | None = None,
        node_filter: str | None = None,
        status_filter: str | None = None,
        run_id_filter: str | None = None,
    ) -> list[Any]: ...

    def prune(self) -> int: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...


@runtime_checkable
class CoalescingQueuePort(Protocol):
    """Protocol for request coalescing/debouncing."""

    @property
    def pending_count(self) -> int: ...

    def submit(self, key: str, callback: Any, data: Any = None) -> bool: ...
    def cancel(self, key: str) -> bool: ...
    def cancel_all(self) -> int: ...


@runtime_checkable
class ConfigWatcherPort(Protocol):
    """Protocol for configuration file hot-reload."""

    @property
    def is_running(self) -> bool: ...

    @property
    def watched_count(self) -> int: ...

    def watch(self, path: Path | str, callback: Any, *, name: str | None = None) -> None: ...
    def unwatch(self, path: Path | str) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def check_now(self) -> int: ...


@runtime_checkable
class LaneQueuePort(Protocol):
    """Protocol for concurrency lane management."""

    def add_lane(self, name: str, *, max_concurrent: int = 1, timeout_s: float = 300.0) -> Any: ...
    def get_lane(self, name: str) -> Any | None: ...
    def list_lanes(self) -> list[str]: ...
    def status(self) -> dict[str, Any]: ...


@runtime_checkable
class StuckDetectorPort(Protocol):
    """Protocol for stuck task detection."""

    @property
    def timeout_s(self) -> float: ...

    @property
    def running_count(self) -> int: ...

    @property
    def is_monitoring(self) -> bool: ...

    def mark_running(self, session_key: str, *, metadata: dict[str, Any] | None = None) -> None: ...
    def mark_completed(self, session_key: str) -> bool: ...
    def check_stuck(self) -> list[str]: ...
    def get_running(self) -> dict[str, float]: ...
    def start_monitor(self) -> None: ...
    def stop_monitor(self) -> None: ...


@runtime_checkable
class TaskGraphPort(Protocol):
    """Protocol for task dependency graph."""

    @property
    def task_count(self) -> int: ...

    @property
    def stats(self) -> Any: ...

    def add_task(self, task: Any) -> None: ...
    def get_task(self, task_id: str) -> Any | None: ...
    def get_ready_tasks(self) -> list[Any]: ...
    def mark_running(self, task_id: str) -> None: ...
    def mark_completed(self, task_id: str, *, result: Any = None) -> None: ...
    def mark_failed(self, task_id: str, *, error: str = "") -> None: ...
    def mark_skipped(self, task_id: str) -> None: ...
    def is_complete(self) -> bool: ...
    def execution_summary(self) -> dict[str, Any]: ...
