"""Auth Ports — Protocol interfaces for authentication and credential management.

Defines abstract contracts for ProfileStore, ProfileRotator, and CooldownTracker,
enabling Clean Architecture dependency inversion.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProfileStorePort(Protocol):
    """Protocol for authentication profile storage."""

    def add(self, profile: Any) -> None: ...
    def get(self, name: str) -> Any | None: ...
    def remove(self, name: str) -> bool: ...
    def list_all(self) -> list[Any]: ...
    def list_by_provider(self, provider: str) -> list[Any]: ...
    def list_available(self, provider: str | None = None) -> list[Any]: ...
    def set_active(self, name: str) -> None: ...
    def get_active(self, provider: str) -> Any | None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...


@runtime_checkable
class ProfileRotatorPort(Protocol):
    """Protocol for credential profile rotation."""

    def resolve(self, provider: str) -> Any | None: ...
    def mark_used(self, profile: Any) -> None: ...
    def mark_success(self, profile: Any) -> None: ...
    def mark_failure(self, profile: Any) -> None: ...
    def disable(self, profile: Any, reason: str) -> None: ...
    def enable(self, profile: Any) -> None: ...
    def get_status(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class CooldownTrackerPort(Protocol):
    """Protocol for API call cooldown tracking."""

    def record_failure(self, key: str, error_type: str = "") -> int: ...
    def record_success(self, key: str) -> None: ...
    def is_available(self, key: str) -> bool: ...
    def get_remaining_ms(self, key: str) -> int: ...
    def clear(self, key: str | None = None) -> None: ...
