/**
 * Portfolio growth data — derived at build time from the synced CHANGELOG
 * (`src/data/geode/changelog.ts`, regenerated by `npm run sync-stats`).
 * Every number on the growth surface comes from this module, not prose.
 */

import { CHANGELOG } from "@/data/geode/changelog";

// Guard against a transient `[Unreleased]` heading in a dev-time sync: only
// dated version entries count as releases.
const releases = CHANGELOG.filter((entry) => /^\d{4}-\d{2}-\d{2}$/.test(entry.date));

// Fail the build loudly instead of dereferencing undefined below — an empty
// list means the changelog sync itself is broken.
if (releases.length === 0) {
  throw new Error("growth.ts: synced changelog contains no dated releases (broken sync-stats run?)");
}

export const releaseCount = releases.length;
export const firstRelease = releases[releases.length - 1];
export const latestRelease = releases[0];

/* ---------------- weekly release cadence (ISO weeks, zero-filled) ------- */

export type WeekBin = {
  /** ISO date (Monday) the bin starts on. */
  start: string;
  count: number;
};

function mondayOfIsoWeek(dateIso: string): Date {
  const [y, m, d] = dateIso.split("-").map(Number);
  const utc = new Date(Date.UTC(y, m - 1, d));
  const dow = utc.getUTCDay() || 7; // Mon=1 .. Sun=7
  utc.setUTCDate(utc.getUTCDate() - (dow - 1));
  return utc;
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export const weeklyCadence: WeekBin[] = (() => {
  const counts = new Map<string, number>();
  for (const entry of releases) {
    const monday = isoDate(mondayOfIsoWeek(entry.date));
    counts.set(monday, (counts.get(monday) ?? 0) + 1);
  }
  const bins: WeekBin[] = [];
  const cursor = mondayOfIsoWeek(firstRelease.date);
  const end = mondayOfIsoWeek(latestRelease.date);
  while (cursor.getTime() <= end.getTime()) {
    const key = isoDate(cursor);
    bins.push({ start: key, count: counts.get(key) ?? 0 });
    cursor.setUTCDate(cursor.getUTCDate() + 7);
  }
  return bins;
})();

export const peakWeek = weeklyCadence.reduce((a, b) => (b.count > a.count ? b : a));

/* ---------------- growth eras ------------------------------------------ */

export type Era = {
  id: string;
  /** Which pixel pose marks this stage of growth. */
  pose: "idle" | "discover" | "focus";
  range: string;
  period: string;
  titleKo: string;
  titleEn: string;
  bodyKo: string;
  bodyEn: string;
  chips: { v: string; ko: string; en: string }[];
};

/**
 * Version/date anchors verified against CHANGELOG entries:
 * 0.6.0=2026-03-10, 0.16.0=03-17, 0.49.0=04-23, 0.66.0=05-06,
 * 0.90.0=05-11, 0.99.0=05-17, 0.99.127=06-03, 0.99.186=06-12,
 * 0.99.225=06-17, 0.99.279=07-06.
 */
export const eras: Era[] = [
  {
    id: "01",
    pose: "idle",
    range: "v0.6.0 ~ v0.16.0",
    period: "2026-03-10 ~ 03-17",
    titleKo: "부화. 그래프를 버리고 루프를 얻다",
    titleEn: "Hatch. Drop the graph, keep the loop",
    bodyKo:
      "LangGraph StateGraph 실행 DAG로 시작한 첫 주입니다. 일주일 만에 그래프를 걷어내고, 도구 호출이 멈출 때까지 도는 while(tool_use) AgenticLoop를 본체로 정했습니다. 이후 모든 것(서브에이전트, 플랜, 배치)은 이 루프의 인스턴스입니다.",
    bodyEn:
      "The first week ran on a LangGraph StateGraph execution DAG. Within that week the graph was removed and the while(tool_use) AgenticLoop became the body. Everything since — sub-agents, plans, batches — is an instance of this loop.",
    chips: [
      { v: "v0.6.0", ko: "MVP", en: "MVP" },
      { v: "v0.8.0", ko: "Plan · Sub-agent", en: "Plan · Sub-agent" },
      { v: "v0.16.0", ko: "AgenticLoop primitive", en: "AgenticLoop primitive" },
    ],
  },
  {
    id: "02",
    pose: "idle",
    range: "v0.16.0 ~ v0.49.0",
    period: "2026-03-17 ~ 04-23",
    titleKo: "골격. 루프 주변에 뼈대를 세우다",
    titleEn: "Skeleton. Building bone around the loop",
    bodyKo:
      "HookSystem 이벤트 버스, subprocess 격리, 4-layer 디렉토리 바인딩, 200K token guard가 이 구간에 들어왔습니다. v0.48에서 hook이 observer에서 interceptor로 확장됐고, v0.49에서 GEODE를 OSS로 공개했습니다.",
    bodyEn:
      "The HookSystem event bus, subprocess isolation, 4-layer directory binding, and the 200K token guard landed here. v0.48 widened hooks from observer to interceptor, and v0.49 opened GEODE as OSS.",
    chips: [
      { v: "v0.24.0", ko: "Codebase audit", en: "Codebase audit" },
      { v: "v0.37.0", ko: "4-Layer bootstrap", en: "4-Layer bootstrap" },
      { v: "v0.48.0", ko: "Hook interceptor", en: "Hook interceptor" },
      { v: "v0.49.0", ko: "OSS 공개", en: "OSS release" },
    ],
  },
  {
    id: "03",
    pose: "discover",
    range: "v0.49.0 ~ v0.99.0",
    period: "2026-04-23 ~ 05-17",
    titleKo: "범용 전환. 도메인을 플러그인 밖으로",
    titleEn: "Generalization. Push the domain out to plugins",
    bodyKo:
      "게임 IP 분석 도구에서 범용 자율 실행 에이전트로 방향을 틀었습니다. 도메인 코드를 플러그인 경계 밖으로 밀어내는 domain-free core 리팩터가 v0.66에서 시작됐고, 4개 프로바이더의 reasoning 배선을 정렬한 R-series 감사, PKCE OAuth 직접 소유(v0.99.0)가 이 구간의 기둥입니다.",
    bodyEn:
      "The pivot from a game-IP analysis tool to a general-purpose autonomous execution agent. The domain-free core refactor that pushes domain code past the plugin boundary started at v0.66; the R-series reasoning wire audit across four providers and owned PKCE OAuth (v0.99.0) anchor this band.",
    chips: [
      { v: "v0.55-62", ko: "R-series reasoning", en: "R-series reasoning" },
      { v: "v0.64.0", ko: "플러그인 경계", en: "Plugin boundary" },
      { v: "v0.66.0", ko: "domain-free core", en: "domain-free core" },
      { v: "v0.99.0", ko: "owned OAuth", en: "owned OAuth" },
    ],
  },
  {
    id: "04",
    pose: "focus",
    range: "v0.90.0 ~ v0.99.186",
    period: "2026-05-11 ~ 06-12",
    titleKo: "자기개선 루프. 스스로를 실험 대상으로",
    titleEn: "Self-improving loop. Itself as the test subject",
    bodyKo:
      "Petri 적대적 안전 감사를 fitness 신호로 삼아 시스템 프롬프트, 도구 정책 같은 스캐폴드를 변이시키기 시작했습니다. critical 축이 후퇴하면 승격을 거부하는 캠페인 게이트, 시드 생성 파이프라인, held-out 벤치, 관측 허브가 이 구간에 쌓였습니다. 모델 가중치는 끝까지 건드리지 않습니다.",
    bodyEn:
      "GEODE started mutating its own scaffold — system prompt, tool policy — with an adversarial Petri safety audit as the fitness signal. Campaign gates that reject any critical-axis regression, the seed-generation pipeline, held-out benches, and the observability hub accumulated here. Model weights stay untouched.",
    chips: [
      { v: "v0.90-93", ko: "Petri wiring", en: "Petri wiring" },
      { v: "v0.99.127", ko: "seedgen Elo blend", en: "seedgen Elo blend" },
      { v: "v0.99.186", ko: "loop guards", en: "loop guards" },
    ],
  },
  {
    id: "05",
    pose: "focus",
    range: "v0.99.225 ~ 현재",
    period: "2026-06-17 ~ ",
    titleKo: "능력 축. 안전 루프를 능력으로 복제",
    titleEn: "Capability axis. Cloning the loop for capability",
    bodyKo:
      "안전 축에서 검증한 promotion protocol을 능력 축으로 복제하는 구간입니다. computer-use 라이브 E2E 왕복(v0.99.225), CLI 라이브 리전과 fleet view 같은 운용 표면, tau2-bench 위에서 통계적 조기 기각을 실험하는 Crucible(v0.99.279)이 진행 중입니다.",
    bodyEn:
      "The promotion protocol proven on the safety axis is being cloned onto capability. Live computer-use E2E round-trips (v0.99.225), operational surfaces like the CLI live region and fleet view, and Crucible (v0.99.279) — statistically rigorous early rejection on tau2-bench — are in flight.",
    chips: [
      { v: "v0.99.225", ko: "computer-use E2E", en: "computer-use E2E" },
      { v: "v0.99.269", ko: "fleet view", en: "fleet view" },
      { v: "v0.99.279", ko: "Crucible", en: "Crucible" },
    ],
  },
];
